"""adding column history_query_rephrase and custom_tool_argument_system_prompt in prompt table

Revision ID: 39a7c37ae834
Revises: 25022707e26f
Create Date: 2025-05-05 11:50:30.411390

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39a7c37ae834"
down_revision = "25022707e26f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt",
        sa.Column("history_query_rephrase", sa.String(), nullable=True)
    )
    op.add_column(
        "prompt",
        sa.Column("custom_tool_argument_system_prompt", sa.String(), nullable=True)
    )