"""adding a field search query prompt and search data source prompt

Revision ID: 8e050b834d25
Revises: 39a7c37ae834
Create Date: 2025-05-13 07:23:19.601899

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8e050b834d25"
down_revision = "39a7c37ae834"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt",
        sa.Column("search_query_prompt", sa.String(), nullable=True)
    )
    op.add_column(
        "prompt",
        sa.Column("search_data_source_selector_prompt", sa.String(), nullable=True)
    )